# Generated by Django 4.1.4 on 2023-06-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('web', 'Web Developmnent'), ('desktop', 'Desktop Development'), ('mobile', 'Mobile Development'), ('network', 'Networking')], max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('briefDisc', models.TextField(max_length=90, null=True)),
                ('FullDisc', models.TextField(max_length=160, null=True)),
                ('oldPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('newPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('specialOffer', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(null=True)),
                ('ReceiveDate', models.DateTimeField(blank=True, null=True)),
                ('SubmitDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customers')),
                ('serviceTable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable')),
            ],
        ),
    ]
